"""refactor system for multi-tenant

Revision ID: 4262d78b9627
Revises: 6b0e7679c46a
Create Date: 2026-03-02 00:19:05.206231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4262d78b9627'
down_revision: Union[str, Sequence[str], None] = '6b0e7679c46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key("fk_audit_logs_user_id", 'audit_logs', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key("fk_audit_logs_organization_id", 'audit_logs', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.add_column('consents', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('consents', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('consents', 'is_granted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_consents_organization_id'), 'consents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.drop_constraint(op.f('consents_user_id_fkey'), 'consents', type_='foreignkey')
    op.create_foreign_key("fk_consents_organization_id", 'consents', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.create_foreign_key("fk_consents_user_id", 'consents', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('login_history', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('login_history', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('login_history', 'login_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('login_history', 'login_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_login_history_organization_id'), 'login_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.drop_constraint(op.f('login_history_user_id_fkey'), 'login_history', type_='foreignkey')
    op.create_foreign_key("fk_login_history_organization_id", 'login_history', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.create_foreign_key("fk_login_history_user_id", 'login_history', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('notifications', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key("fk_notifications_user_id", 'notifications', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key("fk_notifications_organization_id", 'notifications', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.add_column('support_tickets', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_support_tickets_organization_id'), 'support_tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.drop_constraint(op.f('support_tickets_user_id_fkey'), 'support_tickets', type_='foreignkey')
    op.create_foreign_key("fk_support_tickets_organization_id", 'support_tickets', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.create_foreign_key("fk_support_tickets_user_id", 'support_tickets', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_support_tickets_user_id", 'support_tickets', type_='foreignkey')
    op.drop_constraint("fk_support_tickets_organization_id", 'support_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('support_tickets_user_id_fkey'), 'support_tickets', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_organization_id'), table_name='support_tickets')
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('support_tickets', 'organization_id')
    op.drop_constraint("fk_notifications_organization_id", 'notifications', type_='foreignkey')
    op.drop_constraint("fk_notifications_user_id", 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('notifications', 'organization_id')
    op.drop_constraint("fk_login_history_user_id", 'login_history', type_='foreignkey')
    op.drop_constraint("fk_login_history_organization_id", 'login_history', type_='foreignkey')
    op.create_foreign_key(op.f('login_history_user_id_fkey'), 'login_history', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_organization_id'), table_name='login_history')
    op.alter_column('login_history', 'login_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('login_history', 'login_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('login_history', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('login_history', 'organization_id')
    op.drop_constraint("fk_consents_user_id", 'consents', type_='foreignkey')
    op.drop_constraint("fk_consents_organization_id", 'consents', type_='foreignkey')
    op.create_foreign_key(op.f('consents_user_id_fkey'), 'consents', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_organization_id'), table_name='consents')
    op.alter_column('consents', 'is_granted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('consents', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('consents', 'organization_id')
    op.drop_constraint("fk_audit_logs_user_id", 'audit_logs', type_='foreignkey')
    op.drop_constraint("fk_audit_logs_organization_id", 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('audit_logs', 'organization_id')
    # ### end Alembic commands ###
