"""refactor streams for multi-tenant

Revision ID: 6b0e7679c46a
Revises: dd26bf7b498a
Create Date: 2026-03-01 22:48:03.586101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b0e7679c46a'
down_revision: Union[str, Sequence[str], None] = 'dd26bf7b498a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('cameras', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_cameras_organization_id'), 'cameras', ['organization_id'], unique=False)
    op.create_foreign_key("fk_cameras_organization_id", 'cameras', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.add_column('unknown_faces', sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('unknown_faces', sa.Column('resolved_user_id', sa.UUID(), nullable=True))
    op.add_column('unknown_faces', sa.Column('resolved_by', sa.UUID(), nullable=True))
    op.add_column('unknown_faces', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('unknown_faces', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('unknown_faces', 'stream_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('unknown_faces', 'detected_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_unknown_faces_organization_id'), 'unknown_faces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_unknown_faces_resolved_user_id'), 'unknown_faces', ['resolved_user_id'], unique=False)
    op.create_index(op.f('ix_unknown_faces_stream_id'), 'unknown_faces', ['stream_id'], unique=False)
    op.drop_constraint(op.f('unknown_faces_stream_id_fkey'), 'unknown_faces', type_='foreignkey')
    op.create_foreign_key("fk_unknown_faces_resolved_user_id", 'unknown_faces', 'users', ['resolved_user_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key("fk_unknown_faces_stream_id", 'unknown_faces', 'video_streams', ['stream_id'], ['stream_id'], ondelete='CASCADE')
    op.create_foreign_key("fk_unknown_faces_resolved_by", 'unknown_faces', 'users', ['resolved_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key("fk_unknown_faces_organization_id", 'unknown_faces', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.add_column('video_streams', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('video_streams', 'camera_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('video_streams', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_streams', 'processed_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_video_streams_camera_id'), 'video_streams', ['camera_id'], unique=False)
    op.create_index(op.f('ix_video_streams_organization_id'), 'video_streams', ['organization_id'], unique=False)
    op.drop_constraint(op.f('video_streams_camera_id_fkey'), 'video_streams', type_='foreignkey')
    op.create_foreign_key("fk_video_streams_camera_id", 'video_streams', 'cameras', ['camera_id'], ['camera_id'], ondelete='CASCADE')
    op.create_foreign_key("fk_video_streams_organization_id", 'video_streams', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_video_streams_organization_id", 'video_streams', type_='foreignkey')
    op.drop_constraint("fk_video_streams_camera_id", 'video_streams', type_='foreignkey')
    op.create_foreign_key(op.f('video_streams_camera_id_fkey'), 'video_streams', 'cameras', ['camera_id'], ['camera_id'])
    op.drop_index(op.f('ix_video_streams_organization_id'), table_name='video_streams')
    op.drop_index(op.f('ix_video_streams_camera_id'), table_name='video_streams')
    op.alter_column('video_streams', 'processed_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('video_streams', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_streams', 'camera_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('video_streams', 'organization_id')
    op.drop_constraint("fk_unknown_faces_organization_id", 'unknown_faces', type_='foreignkey')
    op.drop_constraint("fk_unknown_faces_resolved_by", 'unknown_faces', type_='foreignkey')
    op.drop_constraint("fk_unknown_faces_resolved_user_id", 'unknown_faces', type_='foreignkey')
    op.drop_constraint("fk_unknown_faces_stream_id", 'unknown_faces', type_='foreignkey')
    op.create_foreign_key(op.f('unknown_faces_stream_id_fkey'), 'unknown_faces', 'video_streams', ['stream_id'], ['stream_id'])
    op.drop_index(op.f('ix_unknown_faces_stream_id'), table_name='unknown_faces')
    op.drop_index(op.f('ix_unknown_faces_resolved_user_id'), table_name='unknown_faces')
    op.drop_index(op.f('ix_unknown_faces_organization_id'), table_name='unknown_faces')
    op.alter_column('unknown_faces', 'detected_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('unknown_faces', 'stream_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('unknown_faces', 'organization_id')
    op.drop_column('unknown_faces', 'resolved_at')
    op.drop_column('unknown_faces', 'resolved_by')
    op.drop_column('unknown_faces', 'resolved_user_id')
    op.drop_column('unknown_faces', 'resolved')
    op.drop_constraint("fk_cameras_organization_id", 'cameras', type_='foreignkey')
    op.drop_index(op.f('ix_cameras_organization_id'), table_name='cameras')
    op.alter_column('cameras', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cameras', 'organization_id')
    # ### end Alembic commands ###
