"""add magic invite token table

Revision ID: 8a570aeeb978
Revises: 9a2c3d4e5f6g
Create Date: 2026-03-29 20:41:25.747401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8a570aeeb978'
down_revision: Union[str, Sequence[str], None] = '9a2c3d4e5f6g'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_invite_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_magic_invite_tokens_department_id'), 'magic_invite_tokens', ['department_id'], unique=False)
    op.create_index(op.f('ix_magic_invite_tokens_organization_id'), 'magic_invite_tokens', ['organization_id'], unique=False)
    op.drop_column('login_history', 'ip_address')
    op.drop_column('login_history', 'user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_history', sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('login_history', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_magic_invite_tokens_organization_id'), table_name='magic_invite_tokens')
    op.drop_index(op.f('ix_magic_invite_tokens_department_id'), table_name='magic_invite_tokens')
    op.drop_table('magic_invite_tokens')
    # ### end Alembic commands ###
