"""refactor attendance for multi-tenant

Revision ID: 966bc821d9ea
Revises: a872a3e20ed2
Create Date: 2026-02-28 15:45:23.707599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '966bc821d9ea'
down_revision: Union[str, Sequence[str], None] = 'a872a3e20ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

attendance_status_enum = ENUM(
    "present", "absent", "half_day", "on_leave",
    name="attendance_status_enum",
    create_type=False,
)

attendance_correction_status_enum = ENUM(
    "pending", "approved", "rejected",
    name="attendance_correction_status_enum",
    create_type=False,
)

attendance_event_type_enum = ENUM(
    "check_in", "check_out", "passby",
    name="attendance_event_type_enum",
    create_type=False,
)

recognition_method_enum = ENUM(
    "face", "live_call",
    name="recognition_method_enum",
    create_type=False,
)

def upgrade() -> None:
    bind = op.get_bind()
    """Upgrade schema."""
    
    # ---- Create ENUM types ----
    attendance_status_enum.create(bind, checkfirst=True)
    attendance_correction_status_enum.create(bind, checkfirst=True)
    attendance_event_type_enum.create(bind, checkfirst=True)
    recognition_method_enum.create(bind, checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('first_check_in', sa.Time(), nullable=True))
    op.add_column('attendance', sa.Column('last_check_out', sa.Time(), nullable=True))
    op.add_column('attendance', sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('attendance', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('attendance', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('attendance', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(),
               type_=attendance_status_enum,
               postgresql_using="status::attendance_status_enum",
               nullable=False)
    op.create_index('ix_attendance_org_user', 'attendance', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_attendance_organization_id'), 'attendance', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_attendance_user_date', 'attendance', ['user_id', 'attendance_date'])
    op.drop_constraint(op.f('attendance_user_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key("fk_attendance_organization", 'attendance', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.create_foreign_key("fk_attendance_user", 'attendance', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('attendance', 'time_out')
    op.drop_column('attendance', 'time_in')
    op.add_column('attendance_corrections', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendance_corrections', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('attendance_corrections', 'attendance_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('attendance_corrections', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('attendance_corrections', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('attendance_corrections', 'status',
               existing_type=sa.VARCHAR(),
               type_=attendance_correction_status_enum,
               postgresql_using="status::attendance_correction_status_enum",
               nullable=False)
    op.alter_column('attendance_corrections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_attendance_corrections_attendance_id'), 'attendance_corrections', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_organization_id'), 'attendance_corrections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_user_id'), 'attendance_corrections', ['user_id'], unique=False)
    op.drop_constraint(op.f('attendance_corrections_reviewed_by_fkey'), 'attendance_corrections', type_='foreignkey')
    op.drop_constraint(op.f('attendance_corrections_attendance_id_fkey'), 'attendance_corrections', type_='foreignkey')
    op.drop_constraint(op.f('attendance_corrections_user_id_fkey'), 'attendance_corrections', type_='foreignkey')
    op.create_foreign_key("fk_att_corr_user", 'attendance_corrections', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key("fk_att_corr_reviewed_by", 'attendance_corrections', 'users', ['reviewed_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key("fk_att_corr_org", 'attendance_corrections', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.create_foreign_key("fk_att_corr_attendance", 'attendance_corrections', 'attendance', ['attendance_id'], ['attendance_id'], ondelete='CASCADE')
    op.add_column('attendance_events', sa.Column("event_type", attendance_event_type_enum, nullable=False))
    op.add_column('attendance_events', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('attendance_events', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('attendance_events', 'scan_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendance_events', 'recognition_method',
               existing_type=sa.VARCHAR(),
               type_=recognition_method_enum,
               postgresql_using="recognition_method::recognition_method_enum",
               nullable=False)
    op.create_index(op.f('ix_attendance_events_camera_id'), 'attendance_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_organization_id'), 'attendance_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_scan_timestamp'), 'attendance_events', ['scan_timestamp'], unique=False)
    op.create_index(op.f('ix_attendance_events_user_id'), 'attendance_events', ['user_id'], unique=False)
    op.drop_constraint(op.f('attendance_events_user_id_fkey'), 'attendance_events', type_='foreignkey')
    op.drop_constraint(op.f('attendance_events_camera_id_fkey'), 'attendance_events', type_='foreignkey')
    op.create_foreign_key("fk_att_event_camera", 'attendance_events', 'cameras', ['camera_id'], ['camera_id'], ondelete='SET NULL')
    op.create_foreign_key("fk_att_event_org", 'attendance_events', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.create_foreign_key("fk_att_event_user", 'attendance_events', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', 'inactive', name='user_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'pending'::user_status_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', 'inactive', name='user_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'pending'::user_status_enum"))
    op.drop_constraint("fk_att_event_user", 'attendance_events', type_='foreignkey')
    op.drop_constraint("fk_att_event_org", 'attendance_events', type_='foreignkey')
    op.drop_constraint("fk_att_event_camera", 'attendance_events', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_events_camera_id_fkey'), 'attendance_events', 'cameras', ['camera_id'], ['camera_id'])
    op.create_foreign_key(op.f('attendance_events_user_id_fkey'), 'attendance_events', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_attendance_events_user_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_scan_timestamp'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_organization_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_camera_id'), table_name='attendance_events')
    op.alter_column('attendance_events', 'recognition_method',
               existing_type=sa.Enum('face', 'live_call', name='recognition_method_enum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attendance_events', 'scan_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendance_events', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('attendance_events', 'organization_id')
    op.drop_column('attendance_events', 'event_type')
    op.drop_constraint("fk_att_corr_attendance", 'attendance_corrections', type_='foreignkey')
    op.drop_constraint("fk_att_corr_org", 'attendance_corrections', type_='foreignkey')
    op.drop_constraint("fk_att_corr_reviewed_by", 'attendance_corrections', type_='foreignkey')
    op.drop_constraint("fk_att_corr_user", 'attendance_corrections', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_corrections_user_id_fkey'), 'attendance_corrections', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('attendance_corrections_attendance_id_fkey'), 'attendance_corrections', 'attendance', ['attendance_id'], ['attendance_id'])
    op.create_foreign_key(op.f('attendance_corrections_reviewed_by_fkey'), 'attendance_corrections', 'users', ['reviewed_by'], ['user_id'])
    op.drop_index(op.f('ix_attendance_corrections_user_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_organization_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_attendance_id'), table_name='attendance_corrections')
    op.alter_column('attendance_corrections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendance_corrections', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='attendance_correction_status_enum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attendance_corrections', 'reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attendance_corrections', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('attendance_corrections', 'attendance_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('attendance_corrections', 'organization_id')
    op.drop_column('attendance_corrections', 'reviewed_at')
    op.add_column('attendance', sa.Column('time_in', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('time_out', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_constraint("fk_attendance_user", 'attendance', type_='foreignkey')
    op.drop_constraint("fk_attendance_organization", 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_user_id_fkey'), 'attendance', 'users', ['user_id'], ['user_id'])
    op.drop_constraint('uq_attendance_user_date', 'attendance', type_='unique')
    op.drop_index(op.f('ix_attendance_organization_id'), table_name='attendance')
    op.drop_index('ix_attendance_org_user', table_name='attendance')
    op.alter_column('attendance', 'status',
               existing_type=sa.Enum('present', 'absent', 'half_day', 'on_leave', name='attendance_status_enum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attendance', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('attendance', 'organization_id')
    op.drop_column('attendance', 'is_deleted')
    op.drop_column('attendance', 'generated_at')
    op.drop_column('attendance', 'last_check_out')
    op.drop_column('attendance', 'first_check_in')
    
    recognition_method_enum.drop(bind, checkfirst=True)
    attendance_event_type_enum.drop(bind, checkfirst=True)
    attendance_correction_status_enum.drop(bind, checkfirst=True)
    attendance_status_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
