"""Allow nullable organization_id for platform super admin

Revision ID: 96e8d69405fc
Revises: 4262d78b9627
Create Date: 2026-03-03 23:57:25.649345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '96e8d69405fc'
down_revision: Union[str, Sequence[str], None] = '4262d78b9627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('attendance_corrections', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('attendance_events', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('audit_logs', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cameras', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('consents', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('departments', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('face_enrollment_sessions', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('facial_biometrics', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('login_history', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('roles', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('support_tickets', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('unknown_faces', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('video_streams', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('voice_biometrics', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_biometrics', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('video_streams', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('unknown_faces', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('support_tickets', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('roles', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('login_history', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('facial_biometrics', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('face_enrollment_sessions', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('departments', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('consents', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('cameras', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('audit_logs', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('attendance_events', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('attendance_corrections', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('attendance', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
