"""initial schema (recreated)

Revision ID: 99a554846585
Revises: 
Create Date: 2026-03-18 11:35:38.604640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99a554846585'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('min_hours_for_present', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'inactive', name='organization_status_enum'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('organization_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('attendance_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status_effect', sa.Enum('present', 'absent', 'half_day', 'on_leave', 'late', name='attendancestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('organization_id', 'start_time', 'end_time', name='uq_attendance_rule_window')
    )
    op.create_index('ix_attendance_rules_org_time', 'attendance_rules', ['organization_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_attendance_rules_organization_id'), 'attendance_rules', ['organization_id'], unique=False)
    op.create_table('cameras',
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('camera_name', sa.String(), nullable=False),
    sa.Column('camera_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('device_identifier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='online', nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_index(op.f('ix_cameras_device_identifier'), 'cameras', ['device_identifier'], unique=True)
    op.create_index(op.f('ix_cameras_organization_id'), 'cameras', ['organization_id'], unique=False)
    op.create_table('departments',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_department_org_name')
    )
    op.create_index('ix_department_org_name', 'departments', ['organization_id', 'name'], unique=False)
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_table('organization_roles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'role_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'active', 'inactive', name='user_status_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('face_enrolled', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_user_org_email')
    )
    op.create_index('ix_user_org_department', 'users', ['organization_id', 'department_id'], unique=False)
    op.create_index('ix_user_org_role', 'users', ['organization_id', 'role_id'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('video_streams',
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('stream_url', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_status', sa.String(), server_default='processing', nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stream_id')
    )
    op.create_index(op.f('ix_video_streams_camera_id'), 'video_streams', ['camera_id'], unique=False)
    op.create_index(op.f('ix_video_streams_organization_id'), 'video_streams', ['organization_id'], unique=False)
    op.create_table('attendance',
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('first_check_in', sa.Time(), nullable=True),
    sa.Column('last_check_out', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('present', 'absent', 'half_day', 'on_leave', 'late', name='attendancestatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('user_id', 'attendance_date', name='uq_attendance_user_date')
    )
    op.create_index('ix_attendance_org_user', 'attendance', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_attendance_organization_id'), 'attendance', ['organization_id'], unique=False)
    op.create_table('attendance_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('scan_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Enum('check_in', 'check_out', 'passby', name='attendanceeventtype'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('recognition_method', sa.Enum('face', 'live_call', name='recognitionmethod'), server_default='face', nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_attendance_events_camera_id'), 'attendance_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_organization_id'), 'attendance_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_scan_timestamp'), 'attendance_events', ['scan_timestamp'], unique=False)
    op.create_index(op.f('ix_attendance_events_user_id'), 'attendance_events', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('consents',
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consent_id')
    )
    op.create_index(op.f('ix_consents_organization_id'), 'consents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('facial_biometrics',
    sa.Column('biometric_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('face_encoding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('biometric_id')
    )
    op.create_index('ix_facial_biometrics_face_encoding', 'facial_biometrics', ['face_encoding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'face_encoding': 'vector_cosine_ops'})
    op.create_index('ix_facial_biometrics_org_user', 'facial_biometrics', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_facial_biometrics_organization_id'), 'facial_biometrics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_facial_biometrics_user_id'), 'facial_biometrics', ['user_id'], unique=False)
    op.create_index('uq_facial_biometrics_user_active_true', 'facial_biometrics', ['organization_id', 'user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('login_history',
    sa.Column('login_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_status', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('login_id')
    )
    op.create_index(op.f('ix_login_history_organization_id'), 'login_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_support_tickets_organization_id'), 'support_tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('unknown_faces',
    sa.Column('unknown_id', sa.UUID(), nullable=False),
    sa.Column('stream_id', sa.UUID(), nullable=False),
    sa.Column('detected_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stream_id'], ['video_streams.stream_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unknown_id')
    )
    op.create_index(op.f('ix_unknown_faces_organization_id'), 'unknown_faces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_unknown_faces_resolved_user_id'), 'unknown_faces', ['resolved_user_id'], unique=False)
    op.create_index(op.f('ix_unknown_faces_stream_id'), 'unknown_faces', ['stream_id'], unique=False)
    op.create_table('voice_biometrics',
    sa.Column('voice_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('voice_encoding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voice_id')
    )
    op.create_index('ix_voice_biometrics_encoding', 'voice_biometrics', ['voice_encoding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'voice_encoding': 'vector_cosine_ops'})
    op.create_index('ix_voice_biometrics_org_user', 'voice_biometrics', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_voice_biometrics_organization_id'), 'voice_biometrics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_voice_biometrics_user_id'), 'voice_biometrics', ['user_id'], unique=False)
    op.create_table('attendance_corrections',
    sa.Column('correction_id', sa.UUID(), nullable=False),
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requested_time_in', sa.Time(), nullable=True),
    sa.Column('requested_time_out', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='attendancecorrectionstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.attendance_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('correction_id')
    )
    op.create_index(op.f('ix_attendance_corrections_attendance_id'), 'attendance_corrections', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_organization_id'), 'attendance_corrections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_attendance_corrections_user_id'), 'attendance_corrections', ['user_id'], unique=False)
    op.create_table('face_enrollment_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('started', 'pending_approval', 'completed', 'failed', name='face_enrollment_status_enum'), nullable=False),
    sa.Column('embedding_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['embedding_id'], ['facial_biometrics.biometric_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_face_enrollment_org_user', 'face_enrollment_sessions', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_face_enrollment_sessions_embedding_id'), 'face_enrollment_sessions', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_face_enrollment_sessions_organization_id'), 'face_enrollment_sessions', ['organization_id'], unique=False)
    op.create_index('ix_face_enrollment_sessions_status', 'face_enrollment_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_face_enrollment_sessions_user_id'), 'face_enrollment_sessions', ['user_id'], unique=False)
    op.create_table('face_enrollment_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['face_enrollment_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_enrollment_images_session_id'), 'face_enrollment_images', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_enrollment_images_session_id'), table_name='face_enrollment_images')
    op.drop_table('face_enrollment_images')
    op.drop_index(op.f('ix_face_enrollment_sessions_user_id'), table_name='face_enrollment_sessions')
    op.drop_index('ix_face_enrollment_sessions_status', table_name='face_enrollment_sessions')
    op.drop_index(op.f('ix_face_enrollment_sessions_organization_id'), table_name='face_enrollment_sessions')
    op.drop_index(op.f('ix_face_enrollment_sessions_embedding_id'), table_name='face_enrollment_sessions')
    op.drop_index('ix_face_enrollment_org_user', table_name='face_enrollment_sessions')
    op.drop_table('face_enrollment_sessions')
    op.drop_index(op.f('ix_attendance_corrections_user_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_organization_id'), table_name='attendance_corrections')
    op.drop_index(op.f('ix_attendance_corrections_attendance_id'), table_name='attendance_corrections')
    op.drop_table('attendance_corrections')
    op.drop_index(op.f('ix_voice_biometrics_user_id'), table_name='voice_biometrics')
    op.drop_index(op.f('ix_voice_biometrics_organization_id'), table_name='voice_biometrics')
    op.drop_index('ix_voice_biometrics_org_user', table_name='voice_biometrics')
    op.drop_index('ix_voice_biometrics_encoding', table_name='voice_biometrics', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'voice_encoding': 'vector_cosine_ops'})
    op.drop_table('voice_biometrics')
    op.drop_index(op.f('ix_unknown_faces_stream_id'), table_name='unknown_faces')
    op.drop_index(op.f('ix_unknown_faces_resolved_user_id'), table_name='unknown_faces')
    op.drop_index(op.f('ix_unknown_faces_organization_id'), table_name='unknown_faces')
    op.drop_table('unknown_faces')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_organization_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_organization_id'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index('uq_facial_biometrics_user_active_true', table_name='facial_biometrics', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_facial_biometrics_user_id'), table_name='facial_biometrics')
    op.drop_index(op.f('ix_facial_biometrics_organization_id'), table_name='facial_biometrics')
    op.drop_index('ix_facial_biometrics_org_user', table_name='facial_biometrics')
    op.drop_index('ix_facial_biometrics_face_encoding', table_name='facial_biometrics', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'face_encoding': 'vector_cosine_ops'})
    op.drop_table('facial_biometrics')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_organization_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendance_events_user_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_scan_timestamp'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_organization_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_camera_id'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_attendance_organization_id'), table_name='attendance')
    op.drop_index('ix_attendance_org_user', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_video_streams_organization_id'), table_name='video_streams')
    op.drop_index(op.f('ix_video_streams_camera_id'), table_name='video_streams')
    op.drop_table('video_streams')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index('ix_user_org_role', table_name='users')
    op.drop_index('ix_user_org_department', table_name='users')
    op.drop_table('users')
    op.drop_table('organization_roles')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_index('ix_department_org_name', table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_cameras_organization_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_device_identifier'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_attendance_rules_organization_id'), table_name='attendance_rules')
    op.drop_index('ix_attendance_rules_org_time', table_name='attendance_rules')
    op.drop_table('attendance_rules')
    op.drop_table('roles')
    op.drop_table('organizations')
    # ### end Alembic commands ###
