"""add min_hours_for_present to organization

Revision ID: 9c05b2f27976
Revises: 9903b1a1a55d
Create Date: 2026-03-16 23:02:26.068811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9c05b2f27976'
down_revision: Union[str, Sequence[str], None] = '9903b1a1a55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get the connection to check for column existence
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('organizations')]

    if 'min_hours_for_present' not in columns:
        op.add_column('organizations', sa.Column('min_hours_for_present', sa.Integer(), nullable=False, server_default='4'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'min_hours_for_present')
    # ### end Alembic commands ###
