"""refactor core for multi-tenant

Revision ID: a872a3e20ed2
Revises: 4c9647acf466
Create Date: 2026-02-28 11:34:17.384810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'a872a3e20ed2'
down_revision: Union[str, Sequence[str], None] = '4c9647acf466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

organization_status_enum = ENUM(
    "active",
    "suspended",
    "inactive",
    name="organization_status_enum",
    create_type=False,
)

user_status_enum = ENUM(
    "pending",
    "approved",
    "rejected",
    "inactive",
    name="user_status_enum",
    create_type=False,
)

def upgrade() -> None:
    bind = op.get_bind()
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types
    organization_status_enum.create(bind, checkfirst=True)
    user_status_enum.create(bind, checkfirst=True)
    
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    
    op.create_table('organizations',
    sa.Column('organization_id', sa.UUID(), primary_key=True, server_default=sa.text("gen_random_uuid()"), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('status', organization_status_enum, nullable=False, server_default="active"),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text("false"),),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.UniqueConstraint('email' , name="uq_organization_email"),
    sa.UniqueConstraint('name', name="uq_organization_name")
    )
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    op.add_column('departments', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_index('ix_department_org_name', 'departments', ['organization_id', 'name'], unique=False)
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_department_org_name', 'departments', ['organization_id', 'name'])
    op.create_foreign_key("fk_departments_organization", 'departments', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.add_column('roles', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('roles_role_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_organization_id'), 'roles', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_role_org_name', 'roles', ['organization_id', 'role_name'])
    op.create_foreign_key("fk_roles_organization", 'roles', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text("true")))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column('users', sa.Column('face_enrolled', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column('users', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    # op.alter_column('users', 'status',
    #            existing_type=sa.VARCHAR(),
    #            type_=user_status_enum,
    #            nullable=False)
    op.execute(
    """
    ALTER TABLE users
    ALTER COLUMN status DROP DEFAULT
    """
    )
    op.execute(
    """
    ALTER TABLE users
    ALTER COLUMN status
    TYPE user_status_enum
    USING status::user_status_enum
    """
    )
    op.execute(
    """
    ALTER TABLE users
    ALTER COLUMN status SET DEFAULT 'pending'
    """
    )
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index('ix_user_org_department', 'users', ['organization_id', 'department_id'], unique=False)
    op.create_index('ix_user_org_role', 'users', ['organization_id', 'role_id'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_unique_constraint('uq_user_org_email', 'users', ['organization_id', 'email'])
    op.drop_constraint(op.f('users_department_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key("fk_users_created_by", 'users', 'users', ['created_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key("fk_users_department", 'users', 'departments', ['department_id'], ['department_id'], ondelete='RESTRICT')
    op.create_foreign_key("fk_users_organization", 'users', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.create_foreign_key("fk_users_approved_by", 'users', 'users', ['approved_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key("fk_users_role", 'users', 'roles', ['role_id'], ['role_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    organization_status_enum.drop(bind, checkfirst=True)
    
    op.drop_constraint("fk_users_created_by", 'users', type_='foreignkey')
    op.drop_constraint("fk_users_approved_by", 'users', type_='foreignkey')
    op.drop_constraint("fk_users_department", 'users', type_='foreignkey')
    op.drop_constraint("fk_users_role", 'users', type_='foreignkey')
    op.drop_constraint("fk_users_organization", 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['role_id'])
    op.create_foreign_key(op.f('users_department_id_fkey'), 'users', 'departments', ['department_id'], ['department_id'])
    op.drop_constraint('uq_user_org_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index('ix_user_org_role', table_name='users')
    op.drop_index('ix_user_org_department', table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'status',
               existing_type=user_status_enum,
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'approved_at')
    op.drop_column('users', 'approved_by')
    op.drop_column('users', 'face_enrolled')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'is_active')
    op.drop_constraint("fk_roles_organization", 'roles', type_='foreignkey')
    op.drop_constraint('uq_role_org_name', 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_organization_id'), table_name='roles')
    op.create_unique_constraint(op.f('roles_role_name_key'), 'roles', ['role_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('roles', 'organization_id')
    op.drop_constraint("fk_departments_organization", 'departments', type_='foreignkey')
    op.drop_constraint('uq_department_org_name', 'departments', type_='unique')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_index('ix_department_org_name', table_name='departments')
    op.drop_column('departments', 'organization_id')
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_table('organizations')
    
    user_status_enum.drop(op.get_bind(), checkfirst=True)
    organization_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
