"""add is_deleted to departments

Revision ID: c218f1f99309
Revises: d6a2a01d6a61
Create Date: 2026-04-05 19:57:36.304363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c218f1f99309'
down_revision: Union[str, Sequence[str], None] = 'd6a2a01d6a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consents_organization_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.add_column('departments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('purge_jobs', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('purge_jobs_organization_id_fkey'), 'purge_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'purge_jobs', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.alter_column('retention_policies', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('retention_policies_organization_id_fkey'), 'retention_policies', type_='foreignkey')
    op.create_foreign_key(None, 'retention_policies', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'retention_policies', type_='foreignkey')
    op.create_foreign_key(op.f('retention_policies_organization_id_fkey'), 'retention_policies', 'organizations', ['organization_id'], ['organization_id'], ondelete='CASCADE')
    op.alter_column('retention_policies', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'purge_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('purge_jobs_organization_id_fkey'), 'purge_jobs', 'organizations', ['organization_id'], ['organization_id'], ondelete='CASCADE')
    op.alter_column('purge_jobs', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('departments', 'is_deleted')
    op.create_table('consents',
    sa.Column('consent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('consent_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_granted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], name=op.f('consents_organization_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('consents_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consent_id', name=op.f('consents_pkey'))
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_index(op.f('ix_consents_organization_id'), 'consents', ['organization_id'], unique=False)
    # ### end Alembic commands ###
