"""Add updated_at column

Revision ID: cd5c87e4b135
Revises: c6e97cd30cc0
Create Date: 2026-03-10 23:54:28.931001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'cd5c87e4b135'
down_revision: Union[str, Sequence[str], None] = 'c6e97cd30cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_enrollment_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['face_enrollment_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('face_enrollment_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('uq_super_admin_platform'), table_name='roles', postgresql_where='(organization_id IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_super_admin_platform'), 'roles', ['role_name'], unique=True, postgresql_where='(organization_id IS NULL)')
    op.drop_column('face_enrollment_sessions', 'updated_at')
    op.drop_table('face_enrollment_images')
    # ### end Alembic commands ###
