"""Updating schema for face enrollment

Revision ID: db5d1044c7ec
Revises: 61aa1a352d79
Create Date: 2026-03-11 13:08:43.735259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db5d1044c7ec'
down_revision: Union[str, Sequence[str], None] = '61aa1a352d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_face_enrollment_images_session_id'), 'face_enrollment_images', ['session_id'], unique=False)
    op.drop_column('face_enrollment_images', 'created_at')
    op.drop_index(op.f('uq_super_admin_platform'), table_name='roles', postgresql_where='(organization_id IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_super_admin_platform'), 'roles', ['role_name'], unique=True, postgresql_where='(organization_id IS NULL)')
    op.add_column('face_enrollment_images', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_face_enrollment_images_session_id'), table_name='face_enrollment_images')
    # ### end Alembic commands ###
