"""refactor biometrics for multi-tenant

Revision ID: dd26bf7b498a
Revises: 966bc821d9ea
Create Date: 2026-03-01 21:42:06.689638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'dd26bf7b498a'
down_revision: Union[str, Sequence[str], None] = '966bc821d9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

face_enrollment_status_enum = ENUM(
    "started",
    "completed",
    "failed",
    name="face_enrollment_status_enum",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    face_enrollment_status_enum.create(bind, checkfirst=True)
    op.create_table('face_enrollment_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', face_enrollment_status_enum, nullable=False),
    sa.Column('embedding_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['embedding_id'], ['facial_biometrics.biometric_id'],name="fk_face_enrollment_embedding", ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'],name="fk_face_enrollment_organization", ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'],name="fk_face_enrollment_user", ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_face_enrollment_org_user', 'face_enrollment_sessions', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_face_enrollment_sessions_embedding_id'), 'face_enrollment_sessions', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_face_enrollment_sessions_organization_id'), 'face_enrollment_sessions', ['organization_id'], unique=False)
    op.create_index('ix_face_enrollment_sessions_status', 'face_enrollment_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_face_enrollment_sessions_user_id'), 'face_enrollment_sessions', ['user_id'], unique=False)
    op.add_column('facial_biometrics', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('facial_biometrics', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column('facial_biometrics', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('facial_biometrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_facial_biometrics_face_encoding', 'facial_biometrics', ['face_encoding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'face_encoding': 'vector_cosine_ops'})
    op.create_index('ix_facial_biometrics_org_user', 'facial_biometrics', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_facial_biometrics_organization_id'), 'facial_biometrics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_facial_biometrics_user_id'), 'facial_biometrics', ['user_id'], unique=False)
    op.create_index('uq_facial_biometrics_user_active_true', 'facial_biometrics', ['organization_id', 'user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_foreign_key("fk_facial_biometrics_organization", 'facial_biometrics', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.add_column('voice_biometrics', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.alter_column("voice_biometrics", "voice_encoding",
                type_=pgvector.sqlalchemy.Vector(512),
                existing_type=pgvector.sqlalchemy.Vector())
    op.alter_column('voice_biometrics', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('voice_biometrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_voice_biometrics_encoding', 'voice_biometrics', ['voice_encoding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'voice_encoding': 'vector_cosine_ops'})
    op.create_index('ix_voice_biometrics_org_user', 'voice_biometrics', ['organization_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_voice_biometrics_organization_id'), 'voice_biometrics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_voice_biometrics_user_id'), 'voice_biometrics', ['user_id'], unique=False)
    op.create_foreign_key("fk_voice_biometrics_organization", 'voice_biometrics', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_constraint("fk_voice_biometrics_organization", 'voice_biometrics', type_='foreignkey')
    op.drop_index(op.f('ix_voice_biometrics_user_id'), table_name='voice_biometrics')
    op.drop_index(op.f('ix_voice_biometrics_organization_id'), table_name='voice_biometrics')
    op.drop_index('ix_voice_biometrics_org_user', table_name='voice_biometrics')
    op.drop_index('ix_voice_biometrics_encoding', table_name='voice_biometrics')
    op.alter_column('voice_biometrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_biometrics', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('voice_biometrics', 'organization_id')
    op.drop_constraint("fk_facial_biometrics_organization", 'facial_biometrics', type_='foreignkey')
    op.drop_index('uq_facial_biometrics_user_active_true', table_name='facial_biometrics', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_facial_biometrics_user_id'), table_name='facial_biometrics')
    op.drop_index(op.f('ix_facial_biometrics_organization_id'), table_name='facial_biometrics')
    op.drop_index('ix_facial_biometrics_org_user', table_name='facial_biometrics')
    op.drop_index('ix_facial_biometrics_face_encoding', table_name='facial_biometrics')
    op.alter_column('facial_biometrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('facial_biometrics', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('facial_biometrics', 'organization_id')
    op.drop_column('facial_biometrics', 'is_active')
    op.drop_index(op.f('ix_face_enrollment_sessions_user_id'), table_name='face_enrollment_sessions')
    op.drop_index('ix_face_enrollment_sessions_status', table_name='face_enrollment_sessions')
    op.drop_index(op.f('ix_face_enrollment_sessions_organization_id'), table_name='face_enrollment_sessions')
    op.drop_index(op.f('ix_face_enrollment_sessions_embedding_id'), table_name='face_enrollment_sessions')
    op.drop_index('ix_face_enrollment_org_user', table_name='face_enrollment_sessions')
    op.drop_table('face_enrollment_sessions')
    face_enrollment_status_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
