"""add notification redirect fields

Revision ID: e3be225392e5
Revises: 99a554846585
Create Date: 2026-03-21 14:45:17.260110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e3be225392e5'
down_revision: Union[str, Sequence[str], None] = '99a554846585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('redirect_path', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('entity_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('event_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'event_type')
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'redirect_path')
    # ### end Alembic commands ###
